# Generated by Django 4.1 on 2023-06-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='title',
        ),
    ]
