# Generated by Django 4.1 on 2023-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_django', '0002_rename_name_comments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
